### ISSUE TITLE
Update NFC and freefare dependencies

### ISSUE THREAD

**Issue by clausecker** [graynk/diversify#1]
Good evening!

A few months ago I have migrated my NFC and Freefare bindings to use Go modules.  I have also since renamed my account from “fuzxxl” to “clausecker.”  As a part of this effort, the imports paths for the `nfc` and `freefare` packages have changes as such:

    import "github.com/clausecker/nfc/v2"
    import "github.com/clausecker/freefare"

As an added bonus, the new import paths are versioned with Go modules for higher stability.  The old import paths will continue to work in projects that do not use Go modules but won't be updated.  Please consider importing the NFC and Freefare modules by the new import paths to keep up to date with future package versions and bug fixes.

**Comment by graynk** [comment]
Hi!

Somehow I missed the notification for this issue since I changed workplaces and didn't really use this project anymore. I've updated the paths and added go.mod as well, thank you
